import { type FormEvent, useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowLeftRight, ArrowRight, Bookmark, CarFront, Check, ChevronDown, CircleHelp, Info, Menu, Plane, Plus, ShieldCheck, Sparkles, TrainFront, TriangleAlert, Waypoints, X } from "lucide-react";
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";

import { developmentPlan, planJourney } from "./api";
import { designIdForCandidate, journeyDesigns, modeDesignIdForCandidate, resultDesigns, type DesignMode } from "./design";
import { buildHandoff } from "./handoffs";
import { PlaceCombobox } from "./PlaceCombobox";
import { candidateCost, candidateForId, candidateLabel, candidateSummary, candidateTitle, costBasis, dateLabel, formatDuration, legDetail, modeImages, modeLabels, routeTitle, transferLabel } from "./presenters";
import { RouteMap } from "./RouteMap";
import { savedJourneys } from "./storage";
import type { Candidate, JourneyLeg, JourneyPlan, Place, SavedJourney } from "./types";

const asset = (name: string) => `/waystory-assets/${name}`;
const today = () => new Date().toISOString().slice(0, 10);
const futureDate = (days: number) => { const value = new Date(); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); };

function Header() {
  const [menuOpen, setMenuOpen] = useState(false); const location = useLocation(); const button = useRef<HTMLButtonElement>(null);
  useEffect(() => setMenuOpen(false), [location.pathname]);
  useEffect(() => { if (!menuOpen) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setMenuOpen(false); button.current?.focus(); } }; document.body.classList.add("ws-menu-visible"); document.addEventListener("keydown", onKey); return () => { document.body.classList.remove("ws-menu-visible"); document.removeEventListener("keydown", onKey); }; }, [menuOpen]);
  return <><header className="ws-header"><Link className="ws-wordmark" to="/">Waystory</Link><button ref={button} className="ws-menu-button" type="button" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={() => setMenuOpen((value) => !value)}>{menuOpen ? <X /> : <Menu />}</button></header>{menuOpen && <MobileMenu close={() => { setMenuOpen(false); button.current?.focus(); }} />}</>;
}
function MobileMenu({ close }: { close: () => void }) { return <section className="ws-mobile-menu" id="mobile-menu" role="dialog" aria-modal="true" aria-label="Menu"><div className="ws-menu-inner"><p className="ws-kicker">Menu</p><h1>Where to next?</h1><nav className="ws-menu-primary" aria-label="Primary navigation"><Link to="/" onClick={close}><span>01</span><div><strong>Plan a journey</strong><small>Start somewhere new.</small></div><ArrowRight /></Link><Link to="/journeys" onClick={close}><span>02</span><div><strong>My journeys</strong><small>Open the plans you saved.</small></div><ArrowRight /></Link></nav><p className="ws-menu-label">Explore</p><nav className="ws-menu-secondary" aria-label="Explore">{["How it works", "Coverage", "Accessibility", "Privacy"].map((item) => <a href={`/#${item.toLowerCase().replaceAll(" ", "-")}`} onClick={close} key={item}>{item}<span>›</span></a>)}</nav><footer className="ws-menu-promise"><i /><h2>Know the whole journey<br />before you go.</h2><p>Journey information should be verified before travel.</p></footer></div></section>; }

function HomePage({ setPlan }: { setPlan: (plan: JourneyPlan) => void }) {
  const navigate = useNavigate(); const [fromText, setFromText] = useState(""); const [toText, setToText] = useState(""); const [origin, setOrigin] = useState<Place | null>(null); const [destination, setDestination] = useState<Place | null>(null); const [date, setDate] = useState(today()); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  function updateOrigin(value: string) { setFromText(value); setOrigin(null); setError(""); }
  function updateDestination(value: string) { setToText(value); setDestination(null); setError(""); }
  async function submit(event: FormEvent) {
    event.preventDefault(); setError("");
    if (!origin || !destination) { setError("Select both locations from the supported-place suggestions."); return; }
    if (origin.place_id === destination.place_id) { setError("From and To must be different places."); return; }
    if (!date || date < today() || date > futureDate(90)) { setError("Choose a departure date from today through the next 90 days."); return; }
    setBusy(true);
    try { const plan = await planJourney(origin.place_id, destination.place_id, date); setPlan(plan); sessionStorage.setItem("waystory.current-plan", JSON.stringify(plan)); navigate("/results"); }
    catch (reason) { setError((reason as Error).message); }
    finally { setBusy(false); }
  }
  function swap() { const nextOrigin = destination; const nextDestination = origin; setOrigin(nextOrigin); setDestination(nextDestination); setFromText(nextOrigin?.name ?? toText); setToText(nextDestination?.name ?? fromText); setError(""); }
  return <main className="ws-home"><section className="ws-home-hero"><p>Door-to-door journeys, clearly explained</p><h1>Know the whole<br />journey before you<br />go.</h1><p>Waystory connects every part of your trip and explains transfers, buffers, costs, confidence, and what you still need to verify.</p><img src={asset("coastal-traveller-with-luggage.png")} alt="Traveller pulling a suitcase" /></section><form className="ws-search-card" onSubmit={submit} noValidate><div className="ws-location-box"><PlaceCombobox label="From" tone="origin" value={fromText} selected={origin} onValueChange={updateOrigin} onSelect={(place) => { setOrigin(place); setFromText(place.name); setError(""); }} pin={<LocationPin tone="origin" />} /><button className="ws-swap" type="button" aria-label="Swap locations" onClick={swap}><ArrowLeftRight /></button><PlaceCombobox label="To" tone="destination" value={toText} selected={destination} onValueChange={updateDestination} onSelect={(place) => { setDestination(place); setToText(place.name); setError(""); }} pin={<LocationPin tone="destination" />} /></div><label className="ws-date"><DateIcon /><span><small>Departure date</small><strong>{dateLabel(date)}</strong></span><input className="ws-date-native" aria-label="Departure date" type="date" min={today()} max={futureDate(90)} value={date} onChange={(event) => { setDate(event.target.value); setError(""); }} /></label>{error && <p className="ws-form-error" role="alert">{error}</p>}<button className="ws-primary" disabled={busy} aria-busy={busy}>{busy ? "Planning your journey…" : "Plan my journey"}</button></form><section className="ws-benefits" aria-label="Benefits"><Benefit icon={<Waypoints />} title="Complete journey">Local transport, main travel, transfers, and arrival.</Benefit><Benefit icon={<CircleHelp />} title="Clear reasoning">Understand why a route is recommended.</Benefit><Benefit icon={<ShieldCheck />} title="Honest guidance">See buffers, confidence, and what must be verified.</Benefit></section><ExampleJourney /><section className="ws-home-cta"><h2>Your journey should make<br />sense before it begins.</h2><a href="#top">Plan a journey</a></section><SiteFooter full /></main>;
}

function ExampleJourney() { return <section className="ws-home-preview"><h2>A complete journey, explained</h2><div className="ws-preview-card"><div className="ws-preview-top"><strong>Illustrative journey</strong><span><Check /> Example</span></div><p>Every local connection and main travel leg appears in one clear plan.</p><dl><div><dt>Duration</dt><dd>Shown as a range</dd></div><div><dt>Estimated cost</dt><dd>Labelled honestly</dd></div><div><dt>Transfers</dt><dd>Traveller actions</dd></div></dl><ol><PreviewStep image="coastal-cab.png" label="Step 1 · Local">Reach the main transport hub</PreviewStep><PreviewStep image="coastal-train.png" label="Step 2 · Main travel">Follow the primary journey leg</PreviewStep><PreviewStep image="coastal-auto-rickshaw.png" label="Step 3 · Arrival">Connect to your destination</PreviewStep></ol><aside><TriangleAlert />Illustration only. Real journey information comes from your selected route and must be verified.</aside></div></section>; }
function LocationPin({ tone }: { tone: "origin" | "destination" }) { return <span className={`ws-pin-illustration ${tone}`} aria-hidden="true"><svg viewBox="0 0 24 36"><path className="pin-body" d="M12 1C5.8 1 2.5 5.3 2.5 10.8c0 7.4 9.5 17.8 9.5 17.8s9.5-10.4 9.5-17.8C21.5 5.3 18.2 1 12 1Z" /><path className="pin-shade" d="M12 1c6.2 0 9.5 4.3 9.5 9.8 0 7.4-9.5 17.8-9.5 17.8 3.1-7.8 3.6-18.9 0-27.6Z" /><circle cx="12" cy="10.5" r="4" fill="#fff" /><path d="M3 29 14.5 26.5 22 30.2 19.3 35 6 34Z" fill="#E5BE79" /><path d="m3 29 8.8 1.2L6 34Z" fill="#F1D59D" /><path d="m11.8 30.2 2.7-3.7 4.8 8.5Z" fill="#D5A45C" /></svg></span>; }
function DateIcon() { return <svg className="ws-date-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="15" rx="3" /><path d="M3 10h18M9 15h6" /></svg>; }
function Benefit({ icon, title, children }: { icon: React.ReactNode; title: string; children: string }) { return <article><span>{icon}</span><p><strong>{title}</strong><small>{children}</small></p></article>; }
function PreviewStep({ image, label, children }: { image: string; label: string; children: string }) { return <li><span><img src={asset(image)} alt="" /></span><p><small>{label}</small><strong>{children}</strong></p></li>; }

function ResultsPage({ plan }: { plan: JourneyPlan }) {
  const navigate = useNavigate(); const [expanded, setExpanded] = useState<string | null>(null); const candidates = plan.candidates.filter((candidate) => candidate.mode !== "air" || candidate.status !== "unavailable"); const available = candidates.filter((candidate) => candidate.status !== "unavailable"); const selected = candidateForId(plan, expanded ?? undefined);
  if (!candidates.length) return <EmptyResults plan={plan} />;
  return <main className={`ws-results ${expanded ? "has-expanded" : ""}`}><section className="ws-results-heading"><Link to="/"><ArrowLeft /> Change journey</Link><div className="ws-route-heading"><div><p>Your journey</p><h1>{plan.origin.name} <span>→</span><br />{plan.destination.name}</h1><small>{dateLabel(plan.travel_date)} · 1 traveller</small></div><Link className="ws-edit-link" to="/">Edit</Link></div><div className="ws-results-copy"><p>Door-to-door options</p><h2>{numberWord(available.length)} {available.length === 1 ? "way" : "ways"} to make<br />this journey.</h2><span>Compare complete journeys—not isolated tickets—and verify changing travel information before departure.</span></div><aside><Info /><span>Times, costs, services, and connections may be estimates. Each option shows what needs checking.</span></aside>{plan.developmentPreview && <p className="ws-preview-notice">Development fixture · not live travel information</p>}</section><section className="ws-result-list" aria-label="Journey results">{candidates.map((candidate) => <ResultCard key={candidate.candidate_id} candidate={candidate} expanded={expanded === candidate.candidate_id} onToggle={() => setExpanded(expanded === candidate.candidate_id ? null : candidate.candidate_id)} onChoose={() => navigate(`/journey/${candidate.candidate_id}`)} />)}</section>{available.length > 1 && <DecisionGuide candidates={available} />}<SiteFooter />{selected && selected.status !== "unavailable" && <div className="ws-results-selection"><p><small>Selected · {candidateLabel(selected)}</small><strong>{candidateTitle(selected)}</strong></p><button type="button" onClick={() => navigate(`/journey/${selected.candidate_id}`)}>Choose journey <ArrowRight /></button></div>}</main>;
}
function ResultCard({ candidate, expanded, onToggle, onChoose }: { candidate: Candidate; expanded: boolean; onToggle: () => void; onChoose: () => void }) { const id = designIdForCandidate(candidate); const style = resultDesigns.find((item) => item.id === modeDesignIdForCandidate(candidate))!; const unavailable = candidate.status === "unavailable"; return <article className={`ws-result-card ws-result-${id} ws-mode-${candidate.mode} ${expanded ? "expanded" : ""} ${unavailable ? "unavailable" : ""}`}><button className="ws-result-summary" type="button" aria-expanded={expanded} aria-controls={`details-${candidate.candidate_id}`} onClick={onToggle}><span className="ws-result-thumb"><img src={asset(style.image)} alt="" /></span><span className="ws-result-label"><strong>{unavailable ? `${modeLabels[candidate.mode]} data unavailable` : candidateLabel(candidate)}</strong>{unavailable && <small>{candidate.unavailable_reason || "Provider data unavailable"}</small>}</span><span className="ws-result-price"><strong>{formatDuration(candidate.total_duration)}</strong><small>{candidateCost(candidate)}</small></span><ChevronDown /></button>{expanded && <ExpandedResult candidate={candidate} onChoose={onChoose} />}</article>; }
function ExpandedResult({ candidate, onChoose }: { candidate: Candidate; onChoose: () => void }) { const style = resultDesigns.find((item) => item.id === modeDesignIdForCandidate(candidate))!; const unavailable = candidate.status === "unavailable"; const comparative = Boolean(candidate.position_explanation && !candidate.position_explanation.startsWith("This is currently the only")); return <div className="ws-expanded-result" id={`details-${candidate.candidate_id}`}><div className="ws-expanded-title"><div><p>{candidate.recommended ? `Recommended ${modeLabels[candidate.mode]} journey` : `${modeLabels[candidate.mode]} journey`}</p><h2>{candidateTitle(candidate)}</h2>{unavailable && <span>{candidate.unavailable_reason}</span>}</div><span><img src={asset(style.image)} alt="" /></span></div>{unavailable ? <UnavailableCandidate candidate={candidate} /> : <><dl><div><dt>Duration</dt><dd>{formatDuration(candidate.total_duration)}</dd></div><div><dt>Estimated cost</dt><dd>{candidateCost(candidate)} <small>{costBasis(candidate)}</small></dd></div><div><dt>Transfers</dt><dd>{transferLabel(candidate)}</dd></div></dl><div className="ws-signals"><span><Sparkles /> {candidate.difficulty.replaceAll("_", " ")}</span><span><Check /> {candidate.confidence} confidence</span></div>{candidate.recommended && comparative && <aside className="ws-why"><Sparkles /><p><strong>Why this journey is recommended</strong><span>{candidate.position_explanation}</span></p></aside>}<ol className="ws-expanded-steps">{candidate.legs.map((leg, index) => <ExpandedStep number={String(index + 1)} leg={leg} candidate={candidate} key={leg.leg_id} />)}</ol><TrustDetails candidate={candidate} /><button className="ws-primary" type="button" onClick={onChoose}>Choose {modeLabels[candidate.mode].toLowerCase()} journey</button></>}</div>; }
function ExpandedStep({ number, leg, candidate }: { number: string; leg: JourneyLeg; candidate: Candidate }) { return <li><span>{number}</span><p><small>Step {number} · {modeLabels[leg.mode]}</small><strong>{leg.instructions || `${leg.origin.name} to ${leg.destination.name}`}</strong><em>{legDetail(leg, candidate)}</em>{leg.intermediate_stops.length > 0 && <em>Stay onboard at: {leg.intermediate_stops.map((stop) => stop.name).join(", ")}</em>}</p><img src={asset(modeImages[leg.mode])} alt="" /></li>; }
function UnavailableCandidate({ candidate }: { candidate: Candidate }) { return <div className="ws-unavailable-result"><Info /><p><strong>{candidate.unavailable_reason || "This option is unavailable."}</strong><span>{candidate.warnings.map((warning) => warning.message).join(" ") || "Waystory will not invent missing route information."}</span></p></div>; }
function TrustDetails({ candidate }: { candidate: Candidate }) { const guidance = candidate.mode === "road" ? ["Traffic and road conditions can change. The self-drive estimate excludes unreported tolls; hired-cab pricing is unavailable. Recheck the route, fuel and tolls before leaving."] : [...candidate.warnings.map((item) => item.message), ...candidate.verification_requirements.filter((item) => item.required).map((item) => item.guidance)]; return <>{guidance.length > 0 && <aside className="ws-check"><TriangleAlert /><p><strong>Check before you go</strong><span>{guidance.join(" ")}</span></p></aside>}<details className="ws-trust-details"><summary>Sources, assumptions and freshness</summary>{candidate.sources.length > 0 && <ul>{candidate.sources.map((source, index) => <li key={`${source.label}-${index}`}><strong>{source.label}</strong> — {source.detail}. Freshness: {source.freshness}{source.last_checked ? `; checked ${dateLabel(source.last_checked, true)}` : ""}.</li>)}</ul>}{candidate.assumptions.length > 0 && <ul>{candidate.assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul>}</details></>; }
function DecisionGuide({ candidates }: { candidates: Candidate[] }) { return <section className="ws-decision"><p>A quick way to decide</p><h2>Which one fits you?</h2><ol>{candidates.map((candidate, index) => <li key={candidate.candidate_id}><span>{String(index + 1).padStart(2, "0")}</span><p><strong>{candidateLabel(candidate)}</strong> {candidate.position_explanation || candidate.unavailable_reason}</p></li>)}</ol></section>; }
function EmptyResults({ plan }: { plan: JourneyPlan }) { return <main className="ws-state-page"><Info /><p>Journey options</p><h1>No trustworthy journey is available yet.</h1><span>{plan.recommendation_explanation || "The available data was not sufficient to construct a defensible journey."}</span><Link to="/">Change journey</Link></main>; }

type TimelineItem = { id: string; mode: string; title: string; meta: string; detail?: string; legIndex: number };
function buildTimeline(candidate: Candidate): TimelineItem[] { const items: TimelineItem[] = []; const used = new Set<string>(); const connections = candidate.connections ?? []; candidate.legs.forEach((leg, legIndex) => { items.push({ id: leg.leg_id, mode: modeLabels[leg.mode].toUpperCase(), title: leg.instructions || `${leg.origin.name} to ${leg.destination.name}`, meta: legDetail(leg, candidate), detail: [leg.service_name && `Service: ${leg.service_name}${leg.service_code ? ` (${leg.service_code})` : ""}`, `${leg.origin.name} → ${leg.destination.name}`].filter(Boolean).join(" · "), legIndex }); leg.intermediate_stops.forEach((stop, index) => items.push({ id: `${leg.leg_id}-stop-${index}`, mode: "STAY ONBOARD", title: stop.name, meta: stop.guidance, legIndex })); connections.filter((connection) => connection.from_leg_id === leg.leg_id).forEach((connection, index) => { const id = connection.connection_id ?? `${leg.leg_id}-connection-${index}`; used.add(id); items.push({ id, mode: connection.kind.replaceAll("_", " ").toUpperCase(), title: connection.location_name, meta: connection.duration ? formatDuration(connection.duration, true) : "Traveller action", detail: `${connection.guidance}${connection.overnight_possible ? " An overnight wait may be possible." : ""}`, legIndex }); }); }); connections.forEach((connection, index) => { const id = connection.connection_id ?? `connection-${index}`; if (!used.has(id)) items.push({ id, mode: connection.kind.replaceAll("_", " ").toUpperCase(), title: connection.location_name, meta: connection.duration ? formatDuration(connection.duration, true) : "Traveller action", detail: connection.guidance, legIndex: Math.max(candidate.legs.findIndex((leg) => leg.leg_id === connection.to_leg_id), 0) }); }); return items; }

const mapMotionRoutes: Record<DesignMode, { path: string; progress: number[] }> = {
  recommended: { path: "M730 1207 C675 1160 626 1140 582 1177 C530 1222 446 1224 395 1195 C349 1169 331 1118 342 1066 C351 1028 316 1012 327 970 C345 903 397 852 412 789 C424 727 423 671 464 626 C489 598 474 548 477 503 C480 452 506 404 532 379 C559 352 575 417 625 417 C679 416 711 382 780 331", progress: [.01, .025, .045, .9, .96, .985, 1] },
  rail: { path: "M730 1207 C675 1160 626 1140 582 1177 C530 1222 446 1224 395 1195 C349 1169 331 1118 342 1066 C351 1028 316 1012 327 970 C345 903 397 852 412 789 C424 727 423 671 464 626 C489 598 474 548 477 503 C480 452 506 404 532 379 C559 352 575 417 625 417 C679 416 711 382 780 331", progress: [.01, .025, .045, .9, .96, .985, 1] },
  road: { path: "M720 1240 C649 1181 568 1190 505 1230 C452 1261 422 1226 425 1167 C429 1118 373 1092 343 1042 C320 1000 349 947 365 902 C383 851 412 813 412 758 C411 700 453 674 466 627 C481 575 463 530 490 479 C517 427 548 371 579 315 C614 277 658 319 705 330 C731 337 750 340 780 350", progress: [.01, .17, .36, .57, .92, 1] },
  flight: { path: "M556 230 C581 300 626 382 646 490 C670 622 663 747 624 873 C575 1034 485 1177 342 1345", progress: [.01, .08, .13, .55, .91, .97, 1] },
};
function MapRoutePointer({ designId, active }: { designId: DesignMode; active: number }) { const previous = useRef(active); const route = mapMotionRoutes[designId]; const from = route.progress[Math.min(previous.current, route.progress.length - 1)] ?? 0; const to = route.progress[Math.min(active, route.progress.length - 1)] ?? 1; useEffect(() => { previous.current = active; }, [active]); return <svg className="ws-map-route-motion" viewBox="0 0 780 1544" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><g key={`${designId}-${active}`}><animateMotion dur="460ms" fill="freeze" path={route.path} keyPoints={`${from};${to}`} keyTimes="0;1" calcMode="spline" keySplines="0.4 0 0.2 1" /><circle className="ws-map-pointer-halo" r="13" /><circle className="ws-map-pointer-dot" r="8" /></g></svg>; }

function JourneyPage({ plan }: { plan: JourneyPlan }) { const { candidateId } = useParams(); const navigate = useNavigate(); const candidate = candidateForId(plan, candidateId); if (!candidate || candidate.status === "unavailable") return <Navigate to="/results" replace />; const designId = designIdForCandidate(candidate); const staticDesign = journeyDesigns[designId]; const dynamicItems = buildTimeline(candidate); const demoItems = staticDesign.steps.map((step, index) => ({ id: `${index}`, mode: step.mode, title: step.title, meta: step.meta, detail: step.detail, legIndex: Math.min(index, candidate.legs.length - 1) })); return <JourneyExperience plan={plan} candidate={candidate} designId={designId} items={plan.developmentPreview ? demoItems : dynamicItems} navigateBack={() => navigate("/results")} />; }
function JourneyExperience({ plan, candidate, designId, items, navigateBack }: { plan: JourneyPlan; candidate: Candidate; designId: DesignMode; items: TimelineItem[]; navigateBack: () => void }) {
  const viewport = useRef<HTMLDivElement>(null); const frame = useRef<number | undefined>(undefined); const [active, setActive] = useState(0); const [saved, setSaved] = useState(savedJourneys.has(plan, candidate.candidate_id)); const handoff = buildHandoff(plan, candidate);
  useEffect(() => () => window.cancelAnimationFrame(frame.current ?? 0), []);
  function onScroll() { const timeline = viewport.current; if (!timeline) return; window.cancelAnimationFrame(frame.current ?? 0); frame.current = window.requestAnimationFrame(() => { const maximum = timeline.scrollHeight - timeline.clientHeight; if (timeline.scrollTop <= 8) { setActive(0); return; } if (maximum - timeline.scrollTop <= 8) { setActive(items.length - 1); return; } const articles = [...timeline.querySelectorAll<HTMLElement>("article")]; const line = timeline.scrollTop + timeline.clientHeight * .42; let nearest = 0; let distance = Infinity; articles.forEach((article, index) => { const next = Math.abs(article.offsetTop + article.offsetHeight / 2 - line); if (next < distance) { nearest = index; distance = next; } }); setActive(nearest); }); }
  function toggleSave() { if (saved) savedJourneys.remove(plan, candidate.candidate_id); else savedJourneys.save(plan, candidate.candidate_id); setSaved(!saved); }
  const current = items[active] ?? items[0]; const staticDesign = journeyDesigns[designId]; const background = plan.developmentPreview ? { backgroundImage: `url(${asset(staticDesign.map)})` } : undefined; const googleRoute = candidate.sources.some((source) => source.label === "Google Maps Routes API");
  return <main className={`ws-journey ws-journey-${designId}`}><div className={`ws-map ${plan.developmentPreview ? "" : "dynamic"}`} style={background}>{!plan.developmentPreview && <RouteMap plan={plan} candidate={candidate} activeLeg={current?.legIndex ?? 0} />}<section className="ws-journey-heading"><button onClick={navigateBack}><ArrowLeft /> Journey options</button><p>{candidate.recommended ? `RECOMMENDED ${modeLabels[candidate.mode].toUpperCase()} JOURNEY` : `${modeLabels[candidate.mode].toUpperCase()} JOURNEY`}</p><h1>{plan.origin.name} →<br />{plan.destination.name}</h1><span>{candidateSummary(candidate)}</span><b>{active + 1} / {items.length}</b><button className="ws-save" type="button" aria-label={saved ? "Remove saved journey" : "Save journey"} aria-pressed={saved} onClick={toggleSave}><Bookmark fill={saved ? "currentColor" : "none"} /></button></section><div className="ws-timeline" ref={viewport} onScroll={onScroll} tabIndex={0} aria-label="Scrollable journey timeline">{items.map((item, index) => <article data-step={index} className={index === active ? "active" : ""} key={item.id}><i /><div><p>{String(index + 1).padStart(2, "0")} · {item.mode}</p><h2>{item.title}</h2><strong>{item.meta}</strong>{item.detail && <span>{item.detail}</span>}</div></article>)}</div>{plan.developmentPreview && <MapRoutePointer designId={designId} active={active} />}<p className="ws-scroll-hint">↕ Scroll each step</p><small className="ws-map-credit">{plan.developmentPreview ? <>Map © CARTO<br />Data © OpenStreetMap contributors</> : googleRoute ? <>Route data © Google Maps</> : <>Route geometry from journey providers<br />© OpenStreetMap contributors</>}</small>{!handoff.prefillSupported && <p className="ws-handoff-fallback">{handoff.fallback}</p>}<div className="ws-journey-action"><p><small>Viewing · {current?.mode}</small><strong>{current?.title}</strong></p><a href={handoff.url} target="_blank" rel="noreferrer">{candidate.mode === "road" ? <CarFront /> : candidate.mode === "air" ? <Plane /> : <TrainFront />}{handoff.label}</a></div></div></main>;
}

function SavedJourneysPage({ setPlan }: { setPlan: (plan: JourneyPlan) => void }) { const navigate = useNavigate(); const [items, setItems] = useState<SavedJourney[]>(savedJourneys.list()); function remove(item: SavedJourney) { savedJourneys.remove(item.plan, item.candidateId); setItems(savedJourneys.list()); } function open(item: SavedJourney) { setPlan(item.plan); sessionStorage.setItem("waystory.current-plan", JSON.stringify(item.plan)); navigate(`/journey/${item.candidateId}`); } return <main className="ws-saved"><section className="ws-saved-heading"><p>Your saved plans</p><h1>My journeys</h1>{items.length > 0 && <span>Everything you chose, ready to open whenever you need it.</span>}</section>{items.length === 0 ? <EmptySaved /> : <><div className="ws-saved-count"><h2>Saved journeys</h2><span>{items.length} saved</span></div><section className="ws-saved-list">{items.map((item) => { const candidate = candidateForId(item.plan, item.candidateId); if (!candidate) return null; const style = resultDesigns.find((result) => result.id === modeDesignIdForCandidate(candidate))!; return <article key={item.id}><div><small>{dateLabel(item.plan.travel_date)} · 1 traveller</small><button type="button" aria-label={`Remove ${routeTitle(item.plan)}`} onClick={() => remove(item)}><Bookmark fill="currentColor" /></button></div><h2>{routeTitle(item.plan)}</h2><section><span><img src={asset(style.image)} alt="" /></span><p><strong>{candidateLabel(candidate)} journey</strong><small>{candidateSummary(candidate)}</small></p></section><button type="button" onClick={() => open(item)}>View journey <ArrowRight /></button></article>; })}</section><Link className="ws-plan-another" to="/"><Plus /> Plan another journey</Link><p className="ws-saved-note">Saved journey details may change. Verify timings before travelling.</p></>}</main>; }
function EmptySaved() { return <section className="ws-empty-saved"><img src={asset("coastal-male-traveller-thinking.png")} alt="Confused traveller with three question marks" /><h2>Bag packed.<br />Destination… anyone?</h2><p>Choose where you’re starting and where you want to go. Waystory will make sense of everything in between.</p><Link to="/">Plan my journey</Link><small>No saved journeys yet. That’s an easy fix.</small></section>; }
function SiteFooter({ full = false }: { full?: boolean }) { return <footer className={`ws-footer ${full ? "full" : ""}`}><strong>Waystory</strong>{full && <nav><a id="how-it-works" href="#how-it-works">How it works</a><a id="coverage" href="#coverage">Coverage</a><a id="accessibility" href="#accessibility">Accessibility</a><a id="privacy" href="#privacy">Privacy</a></nav>}{!full && <h2>Know the whole journey before you go.</h2>}<p>Journey information should be verified before travel.</p></footer>; }
function MissingPlan() { return <main className="ws-state-page"><Info /><p>Journey planner</p><h1>Plan a journey first.</h1><span>Your results are kept only in this browser session.</span><Link to="/">Plan my journey</Link></main>; }
function numberWord(value: number) { return ["No", "One", "Two", "Three", "Four"][value] ?? String(value); }
function readCurrentPlan(): JourneyPlan | null { try { return JSON.parse(sessionStorage.getItem("waystory.current-plan") ?? "null") as JourneyPlan | null; } catch { return null; } }
function AppRoutes() { const [plan, setPlan] = useState<JourneyPlan | null>(() => readCurrentPlan() ?? (import.meta.env.DEV && new URLSearchParams(window.location.search).get("preview") === "1" ? developmentPlan : null)); const location = useLocation(); useEffect(() => { window.scrollTo({ top: 0, behavior: "auto" }); }, [location.pathname]); const results = location.pathname === "/results"; const narrow = results || location.pathname.startsWith("/journey/") || location.pathname === "/journeys"; return <div className={`ws-shell ${narrow ? "narrow" : ""} ${results ? "results-frame" : ""}`} id="top"><Header /><Routes><Route path="/" element={<HomePage setPlan={setPlan} />} /><Route path="/results" element={plan ? <ResultsPage plan={plan} /> : <MissingPlan />} /><Route path="/journey/:candidateId" element={plan ? <JourneyPage plan={plan} /> : <MissingPlan />} /><Route path="/journeys" element={<SavedJourneysPage setPlan={setPlan} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></div>; }
export default function App() { return <AppRoutes />; }
